### ISSUE TITLE
how to prepare motifs.wtmx file

### ISSUE THREAD

**Issue by yuzhenpeng** [hillerlab/REforge#3]
Hi, Hiller

Now, I had the transcription factor for eye development. I want to know how to get the  motifs.wtmx file.
Could you please give me detail instructions.

Thank you.

**Comment by MichaelHiller** [comment]
Hi, 
you can download TF motifs from various sources (Uniprobe, Jaspar, Transfac, ...). 
The format is simple, for each position: 
probA probC probG probT  (must sum to 1). 

Pls see https://github.com/hillerlab/REforge/blob/master/example/data/motifs.wtmx for examples
Michael

**Comment by yuzhenpeng** [comment]
`MEME version 4

ALPHABET= ACGT

strands: + -

Background letter frequencies
A 0.25 C 0.25 G 0.25 T 0.25

MOTIF MA0080.1 SPI1
letter-probability matrix: alength= 4 w= 6 nsites= 57 E= 0
 0.245614  0.368421  0.333333  0.052632
 0.070175  0.035088  0.842105  0.052632
 0.052632  0.000000  0.912281  0.035088
 0.982456  0.017544  0.000000  0.000000
 0.982456  0.000000  0.000000  0.017544
 0.052632  0.315789  0.596491  0.035088
URL http://jaspar.genereg.net/matrix/MA0080.1

MOTIF MA0080.2 SPI1
letter-probability matrix: alength= 4 w= 7 nsites= 42 E= 0
 0.785714  0.071429  0.142857  0.000000
 0.095238  0.000000  0.880952  0.023810
 0.095238  0.000000  0.904762  0.000000
 1.000000  0.000000  0.000000  0.000000
 0.976190  0.000000  0.023810  0.000000
 0.119048  0.071429  0.785714  0.023810
 0.071429  0.119048  0.047619  0.761905
URL http://jaspar.genereg.net/matrix/MA0080.2

MOTIF MA0080.3 Spi1
letter-probability matrix: alength= 4 w= 15 nsites= 63715 E= 0
 0.391697  0.164326  0.275555  0.168422
 0.424876  0.123597  0.345617  0.105909
 0.611567  0.051966  0.216370  0.120097
 0.663125  0.048701  0.188841  0.099333
 0.607110  0.008381  0.180224  0.204285
 0.197395  0.127443  0.675163  0.000000
 0.711857  0.050365  0.230448  0.007330
 0.075351  0.000000  0.924649  0.000000
 0.000000  0.000000  1.000000  0.000000
 0.999215  0.000000  0.000785  0.000000
 1.000000  0.000000  0.000000  0.000000
 0.053928  0.159225  0.786848  0.000000
 0.129483  0.050585  0.053127  0.766805
 0.061100  0.188935  0.714133  0.035831
 0.343891  0.188778  0.329640  0.137691
URL http://jaspar.genereg.net/matrix/MA0080.3

MOTIF MA0080.4 SPI1
letter-probability matrix: alength= 4 w= 14 nsites= 6119 E= 0
 0.644877  0.090701  0.186632  0.077790
 0.911188  0.004761  0.069035  0.015016
 0.992146  0.000393  0.001571  0.005890
 0.980751  0.000000  0.000000  0.019249
 0.899649  0.000739  0.002772  0.096840
 0.008826  0.044308  0.946506  0.000360
 0.272120  0.617393  0.110335  0.000152
 0.005439  0.000188  0.993998  0.000375
 0.000000  0.000188  0.999812  0.000000
 0.999413  0.000392  0.000000  0.000196
 0.998635  0.000195  0.000195  0.000975
 0.000000  0.033880  0.965936  0.000184
 0.004147  0.013626  0.002370  0.979858
 0.507508  0.057658  0.146747  0.288088
URL http://jaspar.genereg.net/matrix/MA0080.4

MOTIF MA0080.5 SPI1
letter-probability matrix: alength= 4 w= 20 nsites= 133203 E= 0
 0.316817  0.169568  0.288319  0.225295
 0.362154  0.159621  0.257329  0.220896
 0.406552  0.151521  0.280332  0.161595
 0.591811  0.085764  0.194388  0.128038
 0.614881  0.092108  0.192038  0.100974
 0.748774  0.021876  0.101191  0.128158
 0.114870  0.082265  0.756927  0.045937
 0.848982  0.025713  0.094172  0.031133
 0.039263  0.004264  0.943695  0.012777
 0.024947  0.007162  0.958229  0.009662
 0.969775  0.010052  0.010563  0.009609
 0.960098  0.005946  0.009820  0.024136
 0.084675  0.074555  0.824321  0.016449
 0.104585  0.027905  0.054286  0.813225
 0.082791  0.095321  0.776897  0.044991
 0.682605  0.084953  0.155004  0.077438
 0.456679  0.150995  0.229552  0.162774
 0.446386  0.127077  0.219124  0.207413
 0.295872  0.197038  0.261473  0.245618
 0.321599  0.186813  0.212720  0.278868
URL http://jaspar.genereg.net/matrix/MA0080.5`

This file I download from jaspar. But I found the format is different with your example.

**Comment by MichaelHiller** [comment]
Pls convert. I think there are converters available, otherwise it is a small script as the probability lines are OK already.

**Comment by yuzhenpeng** [comment]
Thank you. I will complete a script.
